// <auto-generated />
using System;
using CustomTranslator.API.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomTranslator.API.Migrations
{
    [DbContext(typeof(TranslatorContext))]
    [Migration("20221114141207_ChangeFiled")]
    partial class ChangeFiled
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CustomTranslator.API.DataAccess.TranslatorHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FromText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("QueryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ToText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TranslatorHistorys");
                });
#pragma warning restore 612, 618
        }
    }
}
