# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'xjtrab/customTranslatorapi'
        command: 'build'
        Dockerfile: '**/Dockerfile'
    - task: Docker@2
      displayName: Push the image
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'xjtrab/customtranslatorapi'
        command: 'push'
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'tengxun-docker-host'
        contents: 'docker-compose.yml'
        targetFolder: '/opt/teslamate'
        readyTimeout: '20000'
    - task: SSH@0
      inputs:
        sshEndpoint: 'tengxun-docker-host'
        runOptions: 'inline'
        inline: |
          cd /opt/teslamate;
          sudo sed -i 's/##BUILD##/$(Build.BuildId)/g' docker-compose.yml;
          sudo docker-compose up -d --verbose;
        readyTimeout: '20000'